<?php
/**
 * DetailedAthlete
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Strava API v3
 *
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * DetailedAthlete Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DetailedAthlete implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'DetailedAthlete';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'int',
        'resource_state' => 'int',
        'firstname' => 'string',
        'lastname' => 'string',
        'profile_medium' => 'string',
        'profile' => 'string',
        'city' => 'string',
        'state' => 'string',
        'country' => 'string',
        'sex' => 'string',
        'premium' => 'bool',
        'summit' => 'bool',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'follower_count' => 'int',
        'friend_count' => 'int',
        'measurement_preference' => 'string',
        'ftp' => 'int',
        'weight' => 'float',
        'clubs' => '\Swagger\Client\Model\SummaryClub[]',
        'bikes' => '\Swagger\Client\Model\SummaryGear[]',
        'shoes' => '\Swagger\Client\Model\SummaryGear[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => null,
        'resource_state' => null,
        'firstname' => null,
        'lastname' => null,
        'profile_medium' => null,
        'profile' => null,
        'city' => null,
        'state' => null,
        'country' => null,
        'sex' => null,
        'premium' => null,
        'summit' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'follower_count' => null,
        'friend_count' => null,
        'measurement_preference' => null,
        'ftp' => null,
        'weight' => 'float',
        'clubs' => null,
        'bikes' => null,
        'shoes' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'resource_state' => 'resource_state',
        'firstname' => 'firstname',
        'lastname' => 'lastname',
        'profile_medium' => 'profile_medium',
        'profile' => 'profile',
        'city' => 'city',
        'state' => 'state',
        'country' => 'country',
        'sex' => 'sex',
        'premium' => 'premium',
        'summit' => 'summit',
        'created_at' => 'created_at',
        'updated_at' => 'updated_at',
        'follower_count' => 'follower_count',
        'friend_count' => 'friend_count',
        'measurement_preference' => 'measurement_preference',
        'ftp' => 'ftp',
        'weight' => 'weight',
        'clubs' => 'clubs',
        'bikes' => 'bikes',
        'shoes' => 'shoes'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'resource_state' => 'setResourceState',
        'firstname' => 'setFirstname',
        'lastname' => 'setLastname',
        'profile_medium' => 'setProfileMedium',
        'profile' => 'setProfile',
        'city' => 'setCity',
        'state' => 'setState',
        'country' => 'setCountry',
        'sex' => 'setSex',
        'premium' => 'setPremium',
        'summit' => 'setSummit',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'follower_count' => 'setFollowerCount',
        'friend_count' => 'setFriendCount',
        'measurement_preference' => 'setMeasurementPreference',
        'ftp' => 'setFtp',
        'weight' => 'setWeight',
        'clubs' => 'setClubs',
        'bikes' => 'setBikes',
        'shoes' => 'setShoes'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'resource_state' => 'getResourceState',
        'firstname' => 'getFirstname',
        'lastname' => 'getLastname',
        'profile_medium' => 'getProfileMedium',
        'profile' => 'getProfile',
        'city' => 'getCity',
        'state' => 'getState',
        'country' => 'getCountry',
        'sex' => 'getSex',
        'premium' => 'getPremium',
        'summit' => 'getSummit',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'follower_count' => 'getFollowerCount',
        'friend_count' => 'getFriendCount',
        'measurement_preference' => 'getMeasurementPreference',
        'ftp' => 'getFtp',
        'weight' => 'getWeight',
        'clubs' => 'getClubs',
        'bikes' => 'getBikes',
        'shoes' => 'getShoes'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const SEX_M = 'M';
    const SEX_F = 'F';
    const MEASUREMENT_PREFERENCE_FEET = 'feet';
    const MEASUREMENT_PREFERENCE_METERS = 'meters';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSexAllowableValues()
    {
        return [
            self::SEX_M,
            self::SEX_F,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getMeasurementPreferenceAllowableValues()
    {
        return [
            self::MEASUREMENT_PREFERENCE_FEET,
            self::MEASUREMENT_PREFERENCE_METERS,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['resource_state'] = isset($data['resource_state']) ? $data['resource_state'] : null;
        $this->container['firstname'] = isset($data['firstname']) ? $data['firstname'] : null;
        $this->container['lastname'] = isset($data['lastname']) ? $data['lastname'] : null;
        $this->container['profile_medium'] = isset($data['profile_medium']) ? $data['profile_medium'] : null;
        $this->container['profile'] = isset($data['profile']) ? $data['profile'] : null;
        $this->container['city'] = isset($data['city']) ? $data['city'] : null;
        $this->container['state'] = isset($data['state']) ? $data['state'] : null;
        $this->container['country'] = isset($data['country']) ? $data['country'] : null;
        $this->container['sex'] = isset($data['sex']) ? $data['sex'] : null;
        $this->container['premium'] = isset($data['premium']) ? $data['premium'] : null;
        $this->container['summit'] = isset($data['summit']) ? $data['summit'] : null;
        $this->container['created_at'] = isset($data['created_at']) ? $data['created_at'] : null;
        $this->container['updated_at'] = isset($data['updated_at']) ? $data['updated_at'] : null;
        $this->container['follower_count'] = isset($data['follower_count']) ? $data['follower_count'] : null;
        $this->container['friend_count'] = isset($data['friend_count']) ? $data['friend_count'] : null;
        $this->container['measurement_preference'] = isset($data['measurement_preference']) ? $data['measurement_preference'] : null;
        $this->container['ftp'] = isset($data['ftp']) ? $data['ftp'] : null;
        $this->container['weight'] = isset($data['weight']) ? $data['weight'] : null;
        $this->container['clubs'] = isset($data['clubs']) ? $data['clubs'] : null;
        $this->container['bikes'] = isset($data['bikes']) ? $data['bikes'] : null;
        $this->container['shoes'] = isset($data['shoes']) ? $data['shoes'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getSexAllowableValues();
        if (!in_array($this->container['sex'], $allowedValues)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'sex', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getMeasurementPreferenceAllowableValues();
        if (!in_array($this->container['measurement_preference'], $allowedValues)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'measurement_preference', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        $allowedValues = $this->getSexAllowableValues();
        if (!in_array($this->container['sex'], $allowedValues)) {
            return false;
        }
        $allowedValues = $this->getMeasurementPreferenceAllowableValues();
        if (!in_array($this->container['measurement_preference'], $allowedValues)) {
            return false;
        }
        return true;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id The unique identifier of the athlete
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets resource_state
     *
     * @return int
     */
    public function getResourceState()
    {
        return $this->container['resource_state'];
    }

    /**
     * Sets resource_state
     *
     * @param int $resource_state Resource state, indicates level of detail. Possible values: 1 -> \"meta\", 2 -> \"summary\", 3 -> \"detail\"
     *
     * @return $this
     */
    public function setResourceState($resource_state)
    {
        $this->container['resource_state'] = $resource_state;

        return $this;
    }

    /**
     * Gets firstname
     *
     * @return string
     */
    public function getFirstname()
    {
        return $this->container['firstname'];
    }

    /**
     * Sets firstname
     *
     * @param string $firstname The athlete's first name.
     *
     * @return $this
     */
    public function setFirstname($firstname)
    {
        $this->container['firstname'] = $firstname;

        return $this;
    }

    /**
     * Gets lastname
     *
     * @return string
     */
    public function getLastname()
    {
        return $this->container['lastname'];
    }

    /**
     * Sets lastname
     *
     * @param string $lastname The athlete's last name.
     *
     * @return $this
     */
    public function setLastname($lastname)
    {
        $this->container['lastname'] = $lastname;

        return $this;
    }

    /**
     * Gets profile_medium
     *
     * @return string
     */
    public function getProfileMedium()
    {
        return $this->container['profile_medium'];
    }

    /**
     * Sets profile_medium
     *
     * @param string $profile_medium URL to a 62x62 pixel profile picture.
     *
     * @return $this
     */
    public function setProfileMedium($profile_medium)
    {
        $this->container['profile_medium'] = $profile_medium;

        return $this;
    }

    /**
     * Gets profile
     *
     * @return string
     */
    public function getProfile()
    {
        return $this->container['profile'];
    }

    /**
     * Sets profile
     *
     * @param string $profile URL to a 124x124 pixel profile picture.
     *
     * @return $this
     */
    public function setProfile($profile)
    {
        $this->container['profile'] = $profile;

        return $this;
    }

    /**
     * Gets city
     *
     * @return string
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     *
     * @param string $city The athlete's city.
     *
     * @return $this
     */
    public function setCity($city)
    {
        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets state
     *
     * @return string
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param string $state The athlete's state or geographical region.
     *
     * @return $this
     */
    public function setState($state)
    {
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string $country The athlete's country.
     *
     * @return $this
     */
    public function setCountry($country)
    {
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets sex
     *
     * @return string
     */
    public function getSex()
    {
        return $this->container['sex'];
    }

    /**
     * Sets sex
     *
     * @param string $sex The athlete's sex.
     *
     * @return $this
     */
    public function setSex($sex)
    {
        $allowedValues = $this->getSexAllowableValues();
        if (!is_null($sex) && !in_array($sex, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'sex', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['sex'] = $sex;

        return $this;
    }

    /**
     * Gets premium
     *
     * @return bool
     */
    public function getPremium()
    {
        return $this->container['premium'];
    }

    /**
     * Sets premium
     *
     * @param bool $premium Deprecated.  Use summit field instead. Whether the athlete has any Summit subscription.
     *
     * @return $this
     */
    public function setPremium($premium)
    {
        $this->container['premium'] = $premium;

        return $this;
    }

    /**
     * Gets summit
     *
     * @return bool
     */
    public function getSummit()
    {
        return $this->container['summit'];
    }

    /**
     * Sets summit
     *
     * @param bool $summit Whether the athlete has any Summit subscription.
     *
     * @return $this
     */
    public function setSummit($summit)
    {
        $this->container['summit'] = $summit;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at The time at which the athlete was created.
     *
     * @return $this
     */
    public function setCreatedAt($created_at)
    {
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime $updated_at The time at which the athlete was last updated.
     *
     * @return $this
     */
    public function setUpdatedAt($updated_at)
    {
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets follower_count
     *
     * @return int
     */
    public function getFollowerCount()
    {
        return $this->container['follower_count'];
    }

    /**
     * Sets follower_count
     *
     * @param int $follower_count The athlete's follower count.
     *
     * @return $this
     */
    public function setFollowerCount($follower_count)
    {
        $this->container['follower_count'] = $follower_count;

        return $this;
    }

    /**
     * Gets friend_count
     *
     * @return int
     */
    public function getFriendCount()
    {
        return $this->container['friend_count'];
    }

    /**
     * Sets friend_count
     *
     * @param int $friend_count The athlete's friend count.
     *
     * @return $this
     */
    public function setFriendCount($friend_count)
    {
        $this->container['friend_count'] = $friend_count;

        return $this;
    }

    /**
     * Gets measurement_preference
     *
     * @return string
     */
    public function getMeasurementPreference()
    {
        return $this->container['measurement_preference'];
    }

    /**
     * Sets measurement_preference
     *
     * @param string $measurement_preference The athlete's preferred unit system.
     *
     * @return $this
     */
    public function setMeasurementPreference($measurement_preference)
    {
        $allowedValues = $this->getMeasurementPreferenceAllowableValues();
        if (!is_null($measurement_preference) && !in_array($measurement_preference, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'measurement_preference', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['measurement_preference'] = $measurement_preference;

        return $this;
    }

    /**
     * Gets ftp
     *
     * @return int
     */
    public function getFtp()
    {
        return $this->container['ftp'];
    }

    /**
     * Sets ftp
     *
     * @param int $ftp The athlete's FTP (Functional Threshold Power).
     *
     * @return $this
     */
    public function setFtp($ftp)
    {
        $this->container['ftp'] = $ftp;

        return $this;
    }

    /**
     * Gets weight
     *
     * @return float
     */
    public function getWeight()
    {
        return $this->container['weight'];
    }

    /**
     * Sets weight
     *
     * @param float $weight The athlete's weight.
     *
     * @return $this
     */
    public function setWeight($weight)
    {
        $this->container['weight'] = $weight;

        return $this;
    }

    /**
     * Gets clubs
     *
     * @return \Swagger\Client\Model\SummaryClub[]
     */
    public function getClubs()
    {
        return $this->container['clubs'];
    }

    /**
     * Sets clubs
     *
     * @param \Swagger\Client\Model\SummaryClub[] $clubs The athlete's clubs.
     *
     * @return $this
     */
    public function setClubs($clubs)
    {
        $this->container['clubs'] = $clubs;

        return $this;
    }

    /**
     * Gets bikes
     *
     * @return \Swagger\Client\Model\SummaryGear[]
     */
    public function getBikes()
    {
        return $this->container['bikes'];
    }

    /**
     * Sets bikes
     *
     * @param \Swagger\Client\Model\SummaryGear[] $bikes The athlete's bikes.
     *
     * @return $this
     */
    public function setBikes($bikes)
    {
        $this->container['bikes'] = $bikes;

        return $this;
    }

    /**
     * Gets shoes
     *
     * @return \Swagger\Client\Model\SummaryGear[]
     */
    public function getShoes()
    {
        return $this->container['shoes'];
    }

    /**
     * Sets shoes
     *
     * @param \Swagger\Client\Model\SummaryGear[] $shoes The athlete's shoes.
     *
     * @return $this
     */
    public function setShoes($shoes)
    {
        $this->container['shoes'] = $shoes;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


