<?php
/**
 * DetailedSegmentEffortTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Strava API v3
 *
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DetailedSegmentEffortTest Class Doc Comment
 *
 * @category    Class */
// * @description DetailedSegmentEffort
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DetailedSegmentEffortTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DetailedSegmentEffort"
     */
    public function testDetailedSegmentEffort()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "elapsed_time"
     */
    public function testPropertyElapsedTime()
    {
    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "start_date_local"
     */
    public function testPropertyStartDateLocal()
    {
    }

    /**
     * Test attribute "distance"
     */
    public function testPropertyDistance()
    {
    }

    /**
     * Test attribute "is_kom"
     */
    public function testPropertyIsKom()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "activity"
     */
    public function testPropertyActivity()
    {
    }

    /**
     * Test attribute "athlete"
     */
    public function testPropertyAthlete()
    {
    }

    /**
     * Test attribute "moving_time"
     */
    public function testPropertyMovingTime()
    {
    }

    /**
     * Test attribute "start_index"
     */
    public function testPropertyStartIndex()
    {
    }

    /**
     * Test attribute "end_index"
     */
    public function testPropertyEndIndex()
    {
    }

    /**
     * Test attribute "average_cadence"
     */
    public function testPropertyAverageCadence()
    {
    }

    /**
     * Test attribute "average_watts"
     */
    public function testPropertyAverageWatts()
    {
    }

    /**
     * Test attribute "device_watts"
     */
    public function testPropertyDeviceWatts()
    {
    }

    /**
     * Test attribute "average_heartrate"
     */
    public function testPropertyAverageHeartrate()
    {
    }

    /**
     * Test attribute "max_heartrate"
     */
    public function testPropertyMaxHeartrate()
    {
    }

    /**
     * Test attribute "segment"
     */
    public function testPropertySegment()
    {
    }

    /**
     * Test attribute "kom_rank"
     */
    public function testPropertyKomRank()
    {
    }

    /**
     * Test attribute "pr_rank"
     */
    public function testPropertyPrRank()
    {
    }

    /**
     * Test attribute "hidden"
     */
    public function testPropertyHidden()
    {
    }
}
